apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ctx
spec:
  homepage: https://github.com/ahmetb/kubectx
  shortDescription: Switch between contexts in your kubeconfig
  version: v0.9.5-2
  description: |
    Also known as "kubectx", a utility to switch between context entries in
    your kubeconfig file efficiently.
  caveats: |
    If fzf is installed on your machine, you can interactively choose
    between the entries using the arrow keys, or by fuzzy searching
    as you type.
    See https://github.com/RouxAntoine/kubectx for customization and details.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/RouxAntoine/kubectx/releases/download/v0.9.5-2/kubectx_v0.9.5-2_linux_x86_64.tar.gz
    sha256:
    bin: kubectx.sh
    files:
      - from: kubectx.sh
        to: .
      - from: kubectx
        to: .
      - from: LICENSE
        to: .
      - from: completion/plugins/kubectl_complete-ctx
        to: completion/kubectl_complete-ctx
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/RouxAntoine/kubectx/releases/download/v0.9.5-2/kubectx_v0.9.5-2_linux_arm64.tar.gz
    sha256:
    bin: kubectx.sh
    files:
      - from: kubectx.sh
        to: .
      - from: kubectx
        to: .
      - from: LICENSE
        to: .
      - from: completion/plugins/kubectl_complete-ctx
        to: completion/kubectl_complete-ctx
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/RouxAntoine/kubectx/releases/download/v0.9.5-2/kubectx_v0.9.5-2_darwin_x86_64.tar.gz
    sha256:
    bin: kubectx.sh
    files:
      - from: kubectx.sh
        to: .
      - from: kubectx
        to: .
      - from: LICENSE
        to: .
      - from: completion/plugins/kubectl_complete-ctx
        to: completion/kubectl_complete-ctx
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/RouxAntoine/kubectx/releases/download/v0.9.5-2/kubectx_v0.9.5-2_darwin_arm64.tar.gz
    sha256:
    bin: kubectx.sh
    files:
      - from: kubectx.sh
        to: .
      - from: kubectx
        to: .
      - from: LICENSE
        to: .
      - from: completion/plugins/kubectl_complete-ctx
        to: completion/kubectl_complete-ctx
